name: Download OpenAPI Artifact

on:
  workflow_dispatch:

jobs:
  download-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download OpenAPI artifact
        uses: actions/download-artifact@v3
        with:
          name: openapi-docs
          path: accounts/src/main/resources/static/
