name: Build and Upload OpenAPI Artifacts

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-   

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests with Maven Surefire
      run: mvn test        

    - name: Start Spring Boot application
      run: mvn spring-boot:run &
      env:
        SPRING_PROFILES_ACTIVE: test

    - name: Wait for Spring Boot to start
      run: sleep 30

    - name: Generate OpenAPI JSON
      run: curl -o src/main/resources/static/api-docs.json http://localhost:8080/v4/api-docs

    - name: Convert OpenAPI JSON to YAML
      run: |
        pip install json2yaml
        json2yaml src/main/resources/static/api-docs.json > src/main/resources/static/api-docs.yml

    - name: Upload OpenAPI YAML
      uses: actions/upload-artifact@v4
      with:
        name: openapi-yaml
        path: src/main/resources/static/api-docs.yml

  download:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download OpenAPI YAML
      uses: actions/download-artifact@v4
      with:
        name: openapi-yaml
        path: openapi-yaml

    - name: List downloaded files
      run: ls openapi-yaml
