name: Upload OpenAPI Artifact

on:
  push:
    branches:
      - master

jobs:
  upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload OpenAPI artifact
        uses: actions/upload-artifact@v3
        with:
          name: openapi-docs
          path: src/main/resources/static/api-docs.json
